/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop.cellular.view;

/**
 *
 * @author T7144078
 */
public class _CellularGUI extends javax.swing.JFrame {

    /**
     * Creates new form _CellularGUI
     */
    public _CellularGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan_display = new javax.swing.JPanel();
        pan_settings = new javax.swing.JPanel();
        lab_pattern = new javax.swing.JLabel();
        cb_pattern = new javax.swing.JComboBox<>();
        lab_form = new javax.swing.JLabel();
        cb_form = new javax.swing.JComboBox<>();
        lab_size = new javax.swing.JLabel();
        slider_size = new javax.swing.JSlider();
        slider_speed = new javax.swing.JSlider();
        lab_speed = new javax.swing.JLabel();
        pan_controls = new javax.swing.JPanel();
        btn_play = new javax.swing.JButton();
        btn_resume = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lab_stat_form = new javax.swing.JLabel();
        lab_stat_trick = new javax.swing.JLabel();
        lab_stat_live = new javax.swing.JLabel();
        lab_stat_dead = new javax.swing.JLabel();
        lab_stat_runtime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OOP - Cellular Automata - Game of Life");

        pan_display.setBackground(new java.awt.Color(0, 0, 0));
        pan_display.setBorder(new javax.swing.border.SoftBevelBorder(0));

        javax.swing.GroupLayout pan_displayLayout = new javax.swing.GroupLayout(pan_display);
        pan_display.setLayout(pan_displayLayout);
        pan_displayLayout.setHorizontalGroup(
            pan_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pan_displayLayout.setVerticalGroup(
            pan_displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pan_settings.setBorder(javax.swing.BorderFactory.createTitledBorder("Settings"));

        lab_pattern.setText("Pattern");

        cb_pattern.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Random", "Centered" }));

        lab_form.setText("Form");

        cb_form.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Square" }));

        lab_size.setText("Size");

        lab_speed.setText("Speed");

        javax.swing.GroupLayout pan_settingsLayout = new javax.swing.GroupLayout(pan_settings);
        pan_settings.setLayout(pan_settingsLayout);
        pan_settingsLayout.setHorizontalGroup(
            pan_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_settingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_settingsLayout.createSequentialGroup()
                        .addGroup(pan_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lab_pattern)
                            .addComponent(lab_form))
                        .addGap(18, 18, 18)
                        .addGroup(pan_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_form, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_pattern, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pan_settingsLayout.createSequentialGroup()
                        .addGroup(pan_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lab_speed)
                            .addComponent(lab_size))
                        .addGap(18, 18, 18)
                        .addGroup(pan_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(slider_speed, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(slider_size, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pan_settingsLayout.setVerticalGroup(
            pan_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_settingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_pattern)
                    .addComponent(cb_pattern, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pan_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_form)
                    .addComponent(cb_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pan_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab_size)
                    .addComponent(slider_size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pan_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab_speed)
                    .addComponent(slider_speed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pan_controls.setBorder(javax.swing.BorderFactory.createTitledBorder("Controls"));

        btn_play.setText("Play");

        btn_resume.setText("Resume");
        btn_resume.setEnabled(false);

        javax.swing.GroupLayout pan_controlsLayout = new javax.swing.GroupLayout(pan_controls);
        pan_controls.setLayout(pan_controlsLayout);
        pan_controlsLayout.setHorizontalGroup(
            pan_controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_controlsLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(btn_play, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_resume, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pan_controlsLayout.setVerticalGroup(
            pan_controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_controlsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_play)
                    .addComponent(btn_resume))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        lab_stat_form.setText("Form: Square");

        lab_stat_trick.setText("Trick: 0");

        lab_stat_live.setText("Live: 0");

        lab_stat_dead.setText("Dead: 0");

        lab_stat_runtime.setText("Runtime: 0s");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pan_settings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pan_controls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pan_display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lab_stat_form)
                        .addGap(97, 97, 97)
                        .addComponent(lab_stat_trick)
                        .addGap(101, 101, 101)
                        .addComponent(lab_stat_live)
                        .addGap(103, 103, 103)
                        .addComponent(lab_stat_dead)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addComponent(lab_stat_runtime)
                        .addGap(86, 86, 86))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pan_display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pan_settings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pan_controls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_stat_form)
                    .addComponent(lab_stat_trick)
                    .addComponent(lab_stat_live)
                    .addComponent(lab_stat_dead)
                    .addComponent(lab_stat_runtime))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(_CellularGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(_CellularGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(_CellularGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(_CellularGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new _CellularGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_play;
    private javax.swing.JButton btn_resume;
    private javax.swing.JComboBox<String> cb_form;
    private javax.swing.JComboBox<String> cb_pattern;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lab_form;
    private javax.swing.JLabel lab_pattern;
    private javax.swing.JLabel lab_size;
    private javax.swing.JLabel lab_speed;
    private javax.swing.JLabel lab_stat_dead;
    private javax.swing.JLabel lab_stat_form;
    private javax.swing.JLabel lab_stat_live;
    private javax.swing.JLabel lab_stat_runtime;
    private javax.swing.JLabel lab_stat_trick;
    private javax.swing.JPanel pan_controls;
    private javax.swing.JPanel pan_display;
    private javax.swing.JPanel pan_settings;
    private javax.swing.JSlider slider_size;
    private javax.swing.JSlider slider_speed;
    // End of variables declaration//GEN-END:variables
}
